version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: redis
    command: redis-server --requirepass password
    restart: always
    ports:
      - 6379:6379
